---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: cert-check
spec:
  schedule: "* 09 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          #initContainers:
          #  - name: extract-cert
          #    image: openjdk:openjdk/22-ea-jdk-slim-bullseye
          #    command: ["/bin/sh", "-c"]
          #    envFrom:
          #      - secretRef:
          #          name: certinator-certificate-credentials
          #    args: ["keytool -exportcert -keystore /certs/keystore -alias cert_alias -storepass $CERT_PASS -file /certs/my-cert.cer"]
          #    volumeMounts:
          #      - name: transfer
          #        mountPath: /certs
          containers:
            - name: certinator
              image: ghcr.io/gi8lino/certinator:latest
              args:
                - --config=/config/certinator-config.yaml
              envFrom:
                - secretRef:
                    name: certinator-certificate-credentials
              volumeMounts:
                - name: certs
                  mountPath: /certs
                - name: config
                  mountPath: /config
                - name: transfer
                  mountPath: /transfer
          volumes:
            - name: certs
              persistentVolumeClaim:
                claimName: certinator-certs
            - name: config
              configMap:
                name: certinator-config
            - name: transfer
              emptyDir: {}
          restartPolicy: OnFailure
