---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: cert-check
spec:
  schedule: "* 09 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          #initContainers:
          #  - name: extract-cert
          #    image: openjdk:openjdk/22-ea-jdk-slim-bullseye
          #    command: ["/bin/sh", "-c"]
          #    envFrom:
          #      - secretRef:
          #          name: certalert-certificate-credentials
          #    args: ["keytool -exportcert -keystore /certs/keystore -alias cert_alias -storepass $CERT_PASS -file /certs/my-cert.cer"]
          #    volumeMounts:
          #      - name: transfer
          #        mountPath: /certs
          containers:
            - name: certalert
              image: ghcr.io/gi8lino/certalert:latest
              args:
                - --config=/config/certalert-config.yaml
              envFrom:
                - secretRef:
                    name: certalert-certificate-credentials
                - name: RENAMED_JKS_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: certalert-password-file
              volumeMounts:
                - name: certs
                  mountPath: /certs
                - name: config
                  mountPath: /config
                - name: transfer
                  mountPath: /transfer
          volumes:
            - name: certs
              persistentVolumeClaim:
                claimName: certalert-certs
            - name: config
              configMap:
                name: certalert-config
            - name: transfer
              emptyDir: {}
          restartPolicy: OnFailure
