---
apiVersion: v1
kind: Secret
metadata:
  name: certalert-certificate-credentials
type: Opaque
data:
  PEM_PASSWORD: password
  P12_PASSWORD: password
---
apiVersion: v1
kind: Secret
metadata:
  name: certalert-password-file
type: Opaque
data:
  certalert.passwords : |
    jks_password: <top secret>
    another_password: <also secret>
